name: multitask-network
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.0
  - pytables=3.7
  - python=3.9.7
  - pytorch-lightning=1.8
  - rdkit=2022.09.2
  - scikit-learn=1.0.2
  - sqlalchemy~=1.4
